environment:
  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"

build_script:
  # Build the compiled extension
  - "gradlew.bat assemble"

test_script:
  # Run the project tests
  - "gradlew.bat build"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: build\*
